### ISSUE TITLE
[Feature] Add item-selected part for dropdowns in Choice and Combo Boxes

### ISSUE THREAD

**Issue by MatthewHawkins** [DwcJava/engine#458]
**Is your feature request related to a problem? Please describe.**
When trying to style, or exclude, just the active item within a list's dropdown, I don't have a specific part to select to do this.

**Describe the solution you'd like**
Addition of a part item-selected or something similar

**Demo Code to run to see the issue**

```java


import java.util.ArrayList;

import org.dwcj.App;
import org.dwcj.annotation.InlineStyleSheet;
import org.dwcj.component.window.Frame;
import org.dwcj.component.list.ChoiceBox;
import org.dwcj.component.list.ListItem;
import org.dwcj.exceptions.DwcjException;

@InlineStyleSheet("context://css/comboboxstyles/dropdown_styles.css")

public class ChoiceBoxDropdownType extends App {  
  ChoiceBox demoBox = new ChoiceBox("Department");

  @Override
  public void run() throws DwcjException {
    Frame window = new Frame();
    window.addClassName("frame");
    window.add(demoBox);

    ArrayList<ListItem> categories = new ArrayList<>();
    categories.add(new ListItem("Electronics", "Electronics"));
    categories.add(new ListItem("Health and Beauty", "Health and Beauty"));
    categories.add(new ListItem("Fashion", "Fashion"));
    categories.add(new ListItem("Kitchen", "Kitchen"));
    categories.add(new ListItem("Furniture", "Furniture"));
    categories.add(new ListItem("Pet Supplies", "Pet Supplies"));
    categories.add(new ListItem("Toys and Games", "Toys and Games"));

    demoBox.setDropdownType("demo-dropdown-type");
    demoBox.insert(categories)
        .selectIndex(0);
  }
}

```

```css
:root{
  --bbj-list-item-color: #393D48;
  /* --bbj-list-button-label-hover-color: var(--bbj-color-primary-text) */
  --bbj-list-selected-color: white !important;
}

.frame {
  display: flex;
  margin: 20px 0 0 20px;
  width: 200px;
}

[data-dropdown-for="demo-dropdown-type"]::part(list){
  transition: transform 0.3s ease; 
  overflow: hidden;
}

[data-dropdown-for="demo-dropdown-type"]::part(item) {
  transition: transform 0.3s ease, background-color 0.3s ease;
}

[data-dropdown-for="demo-dropdown-type"]::part(item):hover{
  transition: transform 0.3s ease; 
  transform: scale(1.2) translateX(10px);
  color: var(--bbj-color-primary-text);
  cursor: pointer;
}

//Want to add a selector to change hover behavior for selected list item
```
